#%RAML 1.0 DataType
displayName: Accounts
description: Defines the fields in Account Datatype

type: object
properties:
  AccountNumber?: string
  Description?: string
  Name?: string
  NumberOfPeople?: number
  Type?: string
  ID?: number
  LastModifiedId?: string
  LastModifiedDate?: datetime