#%RAML 1.0 DataType
displayName: Contacts
description: Defines the fields in Contacts Datatype

type: object
properties:
  ID?: number
  FirstName?: string
  LastName?: string
  Email?: string
  Description?: string
  Department?: string
  LastModifiedDate?: datetime