#%RAML 1.0 NamedExample

value:
-
  AccountNumber: "1234"
  Description: "Good"
  Name: "Vijay"
  NumberOfPeople: 2
  Type: "personal"
  ID: 345
  LastModifiedId: "23"
  LastModifiedDate: 2019-08-21T04:34:41.098Z
-
  AccountNumber: "4321"
  Description: "Bad"
  Name: "Jhon"
  NumberOfPeople: 1
  Type: "business"
  ID: 123
  LastModifiedId: "12"
  LastModifiedDate: 2019-08-21T04:34:41.098Z