#%RAML 1.0 NamedExample

value:
-
  ID: 101
  FirstName: "VJ"
  LastName: "Reddy"
  Email: "abc@gmail.com"
  Description: "Good"
  Department: "Humanity"
  LastModifiedDate: 2019-08-21T04:34:41.098Z
-
  ID: 94
  FirstName: "Jhon"
  LastName: "Smith"
  Email: "cnn@gmail.com"
  Description: "Bad"
  Department: "Humanity"
  LastModifiedDate: 2019-08-21T04:34:41.098Z